//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

// An System.Collections.ObjectModel.ObservableCollection that raises
// individual item removal notifications on clear and prevents adding duplicates.
public class FixupCollection<T> : ObservableCollection<T>
{
    protected override void ClearItems()
    {
        new List<T>(this).ForEach(t => Remove(t));
    }

    protected override void InsertItem(int index, T item)
    {
        if (!this.Contains(item))
        {
            base.InsertItem(index, item);
        }
    }
}
public partial class CalEvent
{
    #region Primitive Properties

    public virtual int eventId
    {
        get;
        set;
    }

    public virtual string title
    {
        get;
        set;
    }

    public virtual string description
    {
        get;
        set;
    }

    public virtual System.DateTime start_date
    {
        get;
        set;
    }

    public virtual Nullable<System.TimeSpan> start_time
    {
        get;
        set;
    }

    public virtual Nullable<System.DateTime> end_date
    {
        get;
        set;
    }

    public virtual Nullable<System.TimeSpan> end_time
    {
        get;
        set;
    }

    #endregion
}
