//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

public partial class calendarContext : ObjectContext
{
    public const string ConnectionString = "name=calendarContext";
    public const string ContainerName = "calendarContext";

    #region Constructors

    public calendarContext()
        : base(ConnectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public calendarContext(string connectionString)
        : base(connectionString, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    public calendarContext(EntityConnection connection)
        : base(connection, ContainerName)
    {
        this.ContextOptions.LazyLoadingEnabled = true;
    }

    #endregion

    #region ObjectSet Properties

    public ObjectSet<CalEvent> CalEvents
    {
        get { return _calEvents  ?? (_calEvents = CreateObjectSet<CalEvent>("CalEvents")); }
    }
    private ObjectSet<CalEvent> _calEvents;

    #endregion
}
